### ISSUE TITLE
How Code Scripts Interact With Each Other

### ISSUE THREAD

**Issue by solomondaner** [rstudio/shiny-examples#198]
I see the two files "bloomfilter.R" and "global.R"  are being used to get the livestream data. However, although I see some functions in "global.R" being used in Server.R, I don't see those two actual files being imported into Server.R. How does that work? And where are the functions in bloomfilter.R being used in the Server.R code?

**Comment by pyltime** [comment]
Code in a `global.R` file will always be loaded into the global environment of any Shiny app even if not directly loaded in the `server.R` file - see the "Global Objects" section [here](https://shiny.rstudio.com/articles/scoping.html). Since `bloomfilter.R` is being loaded in `global.R`, it gets imported through that. 

The Bloomfilter code gets used in the `global.R` code, which again, is imported by `server.R`.

**Comment by solomondaner** [comment]
I see, what is the benefit in producing 2 additional files outside the Server.R file?

**Comment by jcheng5** [comment]
In this case, for clarity only. For a real app, you might have your functions defined separately if you want to write unit tests for them, or reuse them from a related but separate script/notebook/document.
