### ISSUE TITLE
Why no library(DT) in sample code?

### ISSUE THREAD

**Issue by micstr** [rstudio/shiny-examples#26]
Thanks for your wonderful examples. 

I see you have `DT:::datatable` but I do not see any `library(DT)` in your example ui.R and server.R for the superzip example.

Based on https://rstudio.github.io/DT/shiny.html it seems it is needed, and I am getting namespace errors without it.

Sorry if this is not the right forum. The Shiny gallery Superzip does not show the code so I could  not check it on the gallery, and hence I am in Github.

I am trying to get datatable working for my own app so I am just querying this as a learner.
Thanks
micstr

**Comment by yihui** [comment]
It is okay either to `library(DT)` or not. If you are going to use functions in **DT** frequently in an app, you certainly want to `library(DT)`, otherwise you can use the prefix `DT::` to access functions in **DT**. This is a general R package issue. However, there is an additional issue in **DT** as explained at https://rstudio.github.io/DT/shiny.html Other than `renderDataTable()` and `dataTableOutput()` (just to be careful not to clash with **shiny**), you don't need `DT::`.
