### ISSUE TITLE
How generate PDF/html file direct without click on Download button

### ISSUE THREAD

**Issue by dipenpatel235** [rstudio/shiny-examples#47]
Hello,
I am pass parameter  on url
then depends on url parameter i want to download direct pdf/html file.

but now issue is i need to click on Download button.

so how can i remove that and i can direct get pdf/html  file on uri api call.

Thanks

**Comment by bborgesr** [comment]
If you're referring to the example app number 112 (http://shiny.rstudio.com/gallery/generating-reports.html), I think the easiest way (i.e. without having to change any of Shiny code or do your own JS/jQuery thing) is to simply change the window location to the `href` of the Download Button after some milliseconds. For example, you could include this in your ui function so that the report would be downloaded 100ms after the app starts up:

```r
    tags$head(tags$script("
      $(document).on('shiny:connected', function(event) {
          setTimeout(function() {
            window.location = $('#report').attr('href');
          }, 100);
      })"
    ))
```

**Comment by dipenpatel235** [comment]
that option is not possible ?
url parameter i want to download direct pdf  file.

For example in example app number 112 in i want direct download pdf without open that page with default slider value.

**Comment by bborgesr** [comment]
Hmm, I think I know what you want. Unfortunately, that is not something that we support at the moment.. Sorry.

**Comment by bborgesr** [comment]
Also, it may be worth it to look into [Open CPU](https://www.opencpu.org/) for that use case.
